version: "3.7"

services:
    signatory:
        image: ecadlabs/signatory:latest-${ARCH:-amd64}
        volumes:
            - "./signatory_config/signatory.yaml:/etc/signatory.yaml"
            - "./signatory_config/secret.json:/etc/secret.json"
        command: serve -c /etc/signatory.yaml
        profiles: ["setup"]

    tezossandbox:
        image: oxheadalpha/flextesa:20221026
        command: kathmandubox start
        profiles: ["setup"]

    tzkt-db:
        restart: always
        image: postgres:15
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-tzkt}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
            POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
        profiles: ["setup"]
        volumes:
            - type: tmpfs
              target: /var/lib/postgresql/data:rw
              tmpfs:
                size: 4294967296

    tzkt-api:
        build:
            context: ci/tzkt
            dockerfile: Tzkt.Api/Dockerfile
        restart: on-failure:5
        depends_on:
            - tzkt-sync
        environment:
            ConnectionStrings__DefaultConnection: host=tzkt-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
            Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
        profiles: ["test"]

    tzkt-sync:
        build:
            context: ci/tzkt
            dockerfile: Tzkt.Sync/Dockerfile
        restart: on-failure:5
        depends_on:
            - tezossandbox
            - tzkt-db
        environment:
            ConnectionStrings__DefaultConnection: host=tzkt-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
            TezosNode__Endpoint: http://tezossandbox:20000
        profiles: ["setup"]

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        environment:
            - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=yes
            - TEZOS_RPC_HOST=http://tezossandbox:20000
            - TEZOS_INDEX_HOST=http://tzkt-api:5000
            - SIGNATORY_HOST=http://signatory:6732
        depends_on:
            - signatory
            - tezossandbox
            - tzkt-api
            - tzkt-sync
        command: /app/backend/integration_tests.sh
        profiles: ["test"]
