FROM ocaml/opam:debian-11-ocaml-4.14 as ligobuild
# Checkout a known good commit of the opam-repository, the hash will need updated if we need new released packages
RUN cd ~/opam-repository && git pull origin -q master && git reset --hard 42a177d7ac37cd347aab366a90d20469203fc926 && opam update
RUN sudo apt-get update -qqy \
	&& sudo apt-get install -qy libgmp-dev pkg-config cargo libev-dev \
	&& sudo rm -rf /var/lib/apt/lists/* \
	&& sudo rm -rf /var/cache/apt/*
RUN git clone https://gitlab.com/ligolang/ligo.git
WORKDIR /home/opam/ligo
RUN git checkout 0.50.0

# Bypassing ligo Makefile which generates a new opam switch.
RUN git submodule update --init --recursive
RUN opam install -y --deps-only --with-test . --locked
RUN opam exec -- dune build -p ligo

FROM node:18 AS node

# node is based on debian (libev-dev needed for ligo compiler)
RUN apt-get update -qqy \
	&& apt-get install -qy wget libev-dev \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/apt/*

RUN arch=$(arch | sed s/aarch64/-arm64/ | sed s/x86_64//) && \
	wget -O tezos-client "https://github.com/serokell/tezos-packaging/releases/download/v14.0-1/tezos-client${arch}"
RUN chmod 755 tezos-client
RUN mv tezos-client /bin/tezos-client
RUN tezos-client config reset

COPY --from=ligobuild /home/opam/ligo/_build/install/default/bin/ligo /bin/ligo

WORKDIR /app
COPY . .

WORKDIR /app/cli
RUN npm install -g typescript && npm install
RUN tsc
RUN npm link
RUN chmod 755 /app/cli/integration_tests.sh

WORKDIR /app
RUN make build
