FROM ligolang/ligo:0.50.0 as ligolang

FROM node:18 AS node

# node is based on debian (libev-dev needed for ligo compiler)
RUN apt-get update -qqy \
	&& apt-get install -qy wget libev-dev \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/apt/*

RUN arch=$(arch | sed s/aarch64/-arm64/ | sed s/x86_64//) && \
	wget -O tezos-client "https://github.com/serokell/tezos-packaging/releases/download/v14.0-1/tezos-client${arch}"
RUN chmod 755 tezos-client
RUN mv tezos-client /bin/tezos-client
RUN tezos-client config reset

COPY --from=ligolang /root/ligo /bin/ligo

WORKDIR /app
COPY . .

WORKDIR /app/cli
RUN npm install -g typescript && npm install
RUN tsc
RUN npm link
RUN chmod 755 /app/cli/integration_tests.sh

WORKDIR /app
RUN make build
