FROM ocaml/opam:debian-11-ocaml-4.14 as ligobuild
RUN sudo apt-get update -qqy \
	&& sudo apt-get install -qy libev-dev libgmp-dev pkg-config cargo libev-dev libgmp-dev \
	&& sudo rm -rf /var/lib/apt/lists/* \
	&& sudo rm -rf /var/cache/apt/*
RUN git clone https://gitlab.com/ligolang/ligo.git
WORKDIR /home/opam/ligo
RUN mkdir ./_opam
RUN git checkout 0.50.0
RUN make build-deps
RUN make build

FROM node:18 AS node

# node is based on debian
RUN apt-get update -qqy \
	&& apt-get install -qy wget \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/cache/apt/*

RUN arch=$(arch | sed s/aarch64/-arm64/ | sed s/x86_64//) && \
	wget -O tezos-client "https://github.com/serokell/tezos-packaging/releases/download/v14.0-1/tezos-client${arch}"
RUN chmod 755 tezos-client
RUN mv tezos-client /bin/tezos-client
RUN tezos-client config reset

COPY --from=ligobuild /home/opam/ligo/_build/install/default/bin/ligo /bin/ligo

WORKDIR /app
COPY . .

WORKDIR /app/cli
RUN npm install -g typescript && npm install
RUN tsc
RUN npm link
RUN chmod 755 /app/cli/integration_tests.sh

WORKDIR /app
RUN make build
