# This is a basic workflow to help you get started with Actions

name: CI
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-contracts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install ligo
        run: wget --quiet "https://gitlab.com/ligolang/ligo/-/jobs/3095952199/artifacts/raw/ligo.deb" && sudo dpkg -i ./ligo.deb

      - name: Build and test
        run: make all

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Build
        run: make build

      - name: Test
        run: make test
